services:
  jenkins:
    container_name: ci-server
    # build:
    #   dockerfile: ./alpine/Dockerfile
    #   context: ./alpine
    image: jenkins/jenkins:2.479.3-lts-alpine
    networks:
      - ci-backend
    ports:
      - name: ci-web
        target: 8080
        host_ip: 127.0.0.1
        published: "8080"
        protocol: tcp
        app_protocol: http
        mode: ingress
      - name: ci-agent
        target: 50000
        host_ip: 127.0.0.1
        published: "50000"
        protocol: tcp
        app_protocol: java
        mode: ingress
    volumes:
      # - ci-certs:/certs/client:ro
      - ci-data:/var/jenkins_home:rw
      - type: bind
        source: ./
        target: /local-repository/
        read_only: true

  jenkins-inbound-agent:
    container_name: ci-agent-http
    entrypoint: ["/bin/bash", "-c", "/agent-entrypoint.sh"]
    environment:
      - JENKINS_URL=http://ci-server:8080
      - JENKINS_AGENT_NAME=ci-agent
      - JENKINS_AGENT_WORKDIR=/home/jenkins
    configs:
      - source: agent-http-entrypoint
        target: /agent-entrypoint.sh
        uid: "1000"
        gid: "1000"
        mode: 0777
    image: jenkins/inbound-agent:latest-alpine3.21-jdk17
    networks:
      - ci-backend
    secrets:
      - agent-http-secret
    volumes:
      - ci-agent-http-data:/home/jenkins/agent:rw

  jenkins-ssh-agent:
    configs:
      - source: agent-ssh-entrypoint
        target: /agent-entrypoint.sh
        uid: "1000"
        gid: "1000"
        mode: 0777
    container_name: ci-agent-ssh
    entrypoint: ["/bin/bash", "-c", "/agent-entrypoint.sh"]
    # environment:
    #   - JENKINS_AGENT_SSH_PUBKEY= DEFINED USING ENTRYPOINT

    image: jenkins/ssh-agent:latest-alpine3.21-jdk17
    networks:
      - ci-backend
    ports:
      - name: ci-ssh
        target: 22
        host_ip: 127.0.0.1
        published: "22"
        protocol: tcp
        app_protocol: ssh
        mode: ingress
    secrets:
      - agent-ssh-secret
      - agent-ssh-key
    volumes:
      - ci-agent-ssh-data:/home/jenkins/agent:rw

networks:
  ci-backend:
    driver: bridge
    name: ci-backend

configs:
  agent-http-entrypoint:
    file: ./alpine/jenkins-agent-http/agent-entrypoint.sh
  agent-ssh-entrypoint:
    file: ./alpine/jenkins-agent-ssh/agent-entrypoint.sh

secrets:
  agent-http-secret:
    file: ./alpine/jenkins-agent-http/.agent-secret
  agent-ssh-secret:
    file: ./alpine/jenkins-agent-ssh/.agent-secret
  agent-ssh-key:
    file: ./alpine/jenkins-agent-ssh/.private-key

volumes:
  ci-certs:
    name: ci-certs
  ci-data:
    name: ci-data
  ci-agent-http-data:
    name: ci-agent-http-data
  ci-agent-ssh-data:
    name: ci-agent-ssh-data
